include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    unused_element: error
    unused_import: error
    unused_local_variable: error
    dead_code: error
  exclude:
    - "**/*.g.dart"


linter:
  rules:
    annotate_overrides: false
    overridden_fields: false
    avoid_classes_with_only_static_members: false
    avoid_print: false