include: package:lint/analysis_options.yaml

# IF HELP NEEDED: https://dart-lang.github.io/linter/lints/index.html

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    unused_element: error
    unused_import: error
    unused_local_variable: error
    dead_code: error
  exclude:
    - "lib/**/*.g.dart"
  plugins:
    - moor


linter:
  rules:
    sort_pub_dependencies: false
    package_names: false

    annotate_overrides: false
    overridden_fields: false
    avoid_classes_with_only_static_members: false
    avoid_print: false

    # Doc strings for all public vars
    public_member_api_docs: false
