name: FineWallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2
  moor: ^3.3.1
  moor_flutter: ^3.1.0
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  path_provider: ^1.6.11
  shared_preferences: ^0.5.8
  charts_flutter: ^0.9.0
  flutter_rounded_progress_bar: ^0.1.2
  http: ^0.12.2
  rxdart: ^0.24.1
  dartx: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.3.1
  lint: ^1.2.0
  build_runner:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/monthly_reports.png
    - assets/savings.png


