name: FineWallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  moor: ^2.4.1
  moor_flutter: ^2.1.1
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+2
  charts_flutter: ^0.9.0
  flutter_rounded_progress_bar: ^0.1.2
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0
  lint: ^1.1.1
  build_runner:

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/monthly_reports.png
    - assets/savings.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
